{{- if .Values.configMap.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kube-downscaler.fullname" . }}
data:
  {{- with .Values.configMap.data }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
